apiVersion: v1
kind: Service
metadata:
  name: ribdigi-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ribdigi.backend.labels" . | nindent 4 }}
spec:
  selector:
    app: ribdigi-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
