{{- if .Values.celeryBeat.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ribdigi-celery-beat
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ribdigi.celeryBeat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.celeryBeat.replicaCount }}
  selector:
    matchLabels:
      app: ribdigi-celery-beat
  template:
    metadata:
      labels:
        {{- include "ribdigi.celeryBeat.labels" . | nindent 8 }}
    spec:
      containers:
        - name: celery-beat
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command:
            - celery
            - -A
            - app.celery_app.celery
            - beat
            - --loglevel=info
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          resources:
            {{- toYaml .Values.celeryBeat.resources | nindent 12 }}
{{- end }}
